routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /journal/:
    controller: channel
    filter: primary_tag:journal
  /essay/:
    controller: channel
    filter: primary_tag:essay

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: primary_tag:-newsletter
  /news/:
    permalink: /news/{slug}/
    template: news
    filter: primary_tag:newsletter

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
